### ISSUE TITLE
Broken crypto

### ISSUE THREAD

**Issue by tiffany352** [Habsup/Habsup#1]
First and most horrible of all, it does not use a MAC. Because of the use of CBC mode, any attacker with known plaintext can replace the IV with `iv ^ original_text ^ desired_text` to change the first block to anything they want. A MAC prevents this by verifying the integrity of the message before decrypting it. AES provides confidentiality, not integrity.

Reusing nonces/IVs is a serious security problem, and your code appears to reuse nonces, but it's hard to tell because the code is so bad.

The use of RSA key exchange means that there is no forward secrecy. If keys are ever leaked, all previous sessions will be decryptable. 

My suggestions:

- Use an existing secure protocol. Seriously. DTLS is far more secure than this garbage, and supported by the very OpenSSL library you link for crypto.
- Use libsodium's crypto_box precomputation API using ephemeral keys. It is more secure, faster, and easy to use. It is better than the garbage you are using now. Libsodium is smaller than OpenSSL, and has a nearly flawless security track record.
- Do not roll your own crypto.

**Comment by mark-otaris** [comment]
> The use of RSA key exchange means that there is no forward secrecy. If keys are ever leaked, all previous sessions will be decryptable. 

We planned to use one AES key for each session, and to get rid of the key immediately when a session is closed, but I don't know if that's what the code does right now.

**Comment by JohnMHarrisJr** [comment]
Please migrate this issue to GitLab. This is a mirror of the repository found on GitLab [here](https://gitlab.com/habsup/habsup/).

**Comment by JohnMHarrisJr** [comment]
The initial handshake uses the RSA public key of the intended recipient to send the AES256-CBC session key and IV, followed by the public key of node that is attempting to connect to another. In current code the same key/IV is used for bi-directional communication, though in future this will not be the case.

**Comment by tiffany352** [comment]
@mark-otaris Using a random AES key does not ensure forward secrecy. If the receiving end has their RSA key stolen, then the attacker can decrypt the initial AES key message. This is why RSA key exchange does not have forward secrecy. The only way to ensure forward secrecy is to generate a new key pair for every connection.

**Comment by tiffany352** [comment]
Are you kidding me? Invalid and wontfix? What does it take to get you to fucking fix a complete break in your crypto? This is a trivial exercise on the Matasano Crypto Challenge: http://cryptopals.com/sets/2/challenges/16/

Look at that exercise. It trivially demonstrates how you can break non-MACed CBC crypto. The pseudocode I demonstrated with xor allows an attacker to trivially modify any message sent.

You need a MAC. I am not going to write code specific to your application to demonstrate an extremely general and well-known vulnerability. If you do not fix this, you are lying about any security you claim to have. *Any attacker* can *trivially* modify messages in flight, and you have no protection against this.

This is no pie in the sky issue. This is a serious issue, and it completely compromises the security of this application.

Educate yourself.

http://security.stackexchange.com/questions/33569/why-do-you-need-message-authentication-in-addition-to-encryption
https://en.wikipedia.org/wiki/Message_authentication_code

**Comment by JohnMHarrisJr** [comment]
As you fail to provide any code that can verify this "issue", it will
not be "fixed." If the private key of Habsup trunks is ever, somehow,
gained by a would-be attacker, the entire network would already be at
risk, regardless of the encryption used. If you can provide code that
can, somehow, abuse this "flaw" in Habsup's security, I will be happy to
review your ideas for Habsup's security. Until then, this issue will be
labeled with "wontfix", and, as the label says, will not be "fixed."

**Comment by tiffany352** [comment]
@JohnMHarrisJr This is completely unrelated to the RSA key thing. Not using a MAC does not require any server in any way to have its contents compromised. An attacker which can MITM (for example, a skiddie using software on a laptop at a public hotspot...) can modify the contents of any packets sent over the connection if they are not verified with a MAC. I gave you the information you need to understand this issue, and you have ignored it. I will not try to convince you any further, because you clearly do not wish to change your ignorance. Any existing tools for compromising connections using CBC-mode encryption can be used, I do not need to write code specific to this application. You can google the issue and see that your code is patently vulnerable.

**Comment by JohnMHarrisJr** [comment]
Current code sends the AES256-CBC key and IV encrypted with the public
key of the intended recipient. The public key for every trunk (top level
node) is hard-coded, any changes by "a skiddie using software on a
laptop at a public hotspot" would invalidate the data being sent, the
handshake would fail.
